//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStoreDB_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_Songs
    {
        public int id_album { get; set; }
        public int id_song { get; set; }
        public int id_genre { get; set; }
        public int track_number { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Song Song { get; set; }
    }
}
